name: medimg-coronary-v1

channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - libcxx=20.1.8
  - libexpat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pytest=9.0.2
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.1
  - tk=8.6.15
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - annotated-types==0.7.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - exceptiongroup==1.3.1
      - filelock==3.20.3
      - fonttools==4.61.1
      - fsspec==2026.1.0
      - imageio==2.37.2
      - importlib-resources==6.5.2
      - iniconfig==2.3.0
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - monai==1.5.1
      - mpmath==1.3.0
      - networkx==3.4.2
      - nibabel==5.3.3
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.1.0
      - pluggy==1.6.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydicom==3.0.1
      - pygments==2.19.2
      - pyparsing==3.3.1
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - scikit-image==0.25.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - simpleitk==2.5.3
      - six==1.17.0
      - sympy==1.14.0
      - tifffile==2025.5.10
      - tomli==2.4.0
      - torch==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
prefix: /Users/reneeqian/miniconda3/envs/medimg-base
